package com.travel.smartcity.service;

import com.travel.smartcity.dao.PaymentDAO;
import com.travel.smartcity.model.Payment;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public class PaymentService {
  private PaymentDAO paymentDAO = new PaymentDAO();

  public boolean recordPayment(int userId,
                               int bookingId,
                               BigDecimal amount,
                               String method,
                               String status) {
    return paymentDAO.createPayment(userId, bookingId, amount, method, status);
  }


//  public boolean processPayment(Payment payment) {
//    return paymentDAO.create(payment);
//  }
//
//  public List<Payment> getPaymentsForUser(int userId) {
//    return paymentDAO.findByUserId(userId);
//  }
//
//
//  /**
//   * Convenience method: process payment using card details.
//   * In a real app, integrate with a gateway here.
//   */
//  public boolean process(String cardNumber, String expiry) {
//    // Basic validation of inputs
//    if (cardNumber == null || cardNumber.isBlank() || expiry == null || expiry.isBlank()) {
//      return false;
//    }
//    // TODO: integrate with payment gateway using cardNumber & expiry
//    // For demo purposes, record a dummy payment with placeholders:
//    Payment payment = new Payment(
//            0,                  // id placeholder (auto-generated by DB)
//            1,                  // userId placeholder; retrieve from session/context
//            1,                  // payeeId placeholder; pass or select in controller
//            BigDecimal.ZERO,    // amount placeholder; set actual amount
//            LocalDateTime.now() // current timestamp
//    );
//    return processPayment(payment);
//  }
}